### ISSUE TITLE
Failing to crawl The Cook's Thesaurus (https://foodsubs.com/)

### ISSUE THREAD

**Issue by kondilidisn** [solashirai/FoodSubstitutionDataScripts#2]
Hi, 

First of all, thank you very much for all your work and effort so far!
I am trying to replicate your work, and I think I fail to crawl the https://foodsubs.com/ website, because the "scraped_pages" directory only has a file named "subs_foodsubs.com_.html" that is 10KB big.

[EDIT]
The error that I later get is when executing the script 'soup_extract_subs_from_pages' and it more or less says that there were no files with substitutes found in directory 'scraped_pages'. I am also trying to make it work meanwhile, will post here when I have any updates.

Best,
Nikos.

**Comment by solashirai** [comment]
Hi,

I'm afraid that all of the code to craw foodsubs.com is probably completely deprecated, because after performing this work their website underwent a major renovation in structure.
Related to the major website changes, we couldn't receive permission to publicly release the substitution data that we scraped from their website.

Given that permissions to do webscraping over their website is dubious, I don't have any plans to update this part of the code.

Some substitution data can still be acquired from the Food.com data (scripts in `parse_fooddotcom_reviews/`), which I believe can be used in place of the foodsubs data for other experiments in this repo. A lot of the documentation for using the experiment code is currently out of date with the publicly available FoodKG construction code though, so updated documentation to fix a variety of errors is still in the works.

**Comment by kondilidisn** [comment]
Thank you very much for your help and contribution, I extracted the substitutions from the Food.com - kaggle dataset.

Meanwhile I also created an updated version of a scrapy spider that saves all information of FoodSubs.com in the form of knowledge graph, containing ingredient information and ingredient substitutions. I will try to see if it can be of any use given the position of the new administration of the website. I will keep you updated if I have any news, and please contact me if you think this spider could be useful to you.
